import {
  Geist,
  Geist_Mono,
  Great_Vibes,
  Nanum_Myeongjo
} from "next/font/google";
import "./globals.css";
import '@fontsource/nanum-myeongjo'
import Navbar from "@/components/custom/Navbar";

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` not-[]:${greatVibes.className}  antialiased`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
